# SITE SETTINGS
title: Darwin Core

# SOCIAL PROFILES
social:
  github: tdwg/dwc

# THEME SETTINGS
theme: minima
remote_theme: tdwg/petridish
github_edit: false
logo: /assets/theme/images/tdwg-logo-short.svg

# BUILD SETTINGS
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE

# FRONTMATTER DEFAULTS
defaults:
  - scope:
      path: ""
    values:
      layout: default
      toc: true
  - scope:
      path: pages/en
    values:
      language: en
      permalink: /:basename/
      navigation: navigation_en
  - scope:
      path: pages/nl
    values:
      language: nl
      permalink: /nl/:basename/
      navigation: navigation_nl

